/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "surface-tint": "#ffb877",
        "primary-fixed-dim": "#ffb877",
        "secondary-fixed-dim": "#45dfa4",
        "on-surface": "#e6e1df",
        "surface-container-high": "#2b2a28",
        "secondary": "#45dfa4",
        "tertiary-fixed": "#c2e8ff",
        "inverse-on-surface": "#32302f",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#00c0fd",
        "surface-variant": "#363433",
        "error-container": "#93000a",
        "outline": "#a28d7c",
        "outline-variant": "#554335",
        "on-tertiary-container": "#004a65",
        "surface-container": "#211f1e",
        "primary-fixed": "#ffdcc1",
        "on-tertiary-fixed-variant": "#004d67",
        "surface-bright": "#3b3937",
        "on-primary-container": "#693900",
        "on-secondary-fixed-variant": "#005137",
        "primary-container": "#ff9a2e",
        "surface-container-low": "#1d1b1a", "surface-card": "#1a1918", "surface-low": "#191817", "surface-elevated": "#2a2827",
        "on-primary-fixed": "#2e1500",
        "on-primary-fixed-variant": "#6c3a00",
        "background": "#141312",
        "on-primary": "#4c2700",
        "tertiary-fixed-dim": "#76d1ff",
        "surface": "#141312",
        "tertiary": "#8dd7ff",
        "inverse-primary": "#8e4f00",
        "surface-container-lowest": "#0f0e0d",
        "on-secondary-container": "#00452e",
        "on-background": "#e6e1df",
        "on-tertiary-fixed": "#001e2b",
        "surface-dim": "#141312",
        "secondary-fixed": "#68fcbf",
        "error": "#ffb4ab",
        "on-tertiary": "#003548",
        "inverse-surface": "#e6e1df",
        "primary": "#ffc18c",
        "on-secondary-fixed": "#002114",
        "secondary-container": "#00bd85",
        "on-surface-variant": "#dbc2af",
        "surface-container-highest": "#363433",
        "on-secondary": "#003825",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.5rem",
        "margin-tablet": "2rem",
        "space-xl": "2rem",
        "space-md": "1rem",
        "gutter": "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "margin": "1.25rem",
        "margin-desktop": "3rem",
      },
      fontFamily: {
        "label-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "label-caps": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-metric": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "label-md": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "54px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-metric": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
